version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hr_platform
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d hr_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      DATABASE_URL: postgresql://hr_user:hr_password@postgres:5432/hr_platform
      SECRET_KEY: your-secret-key-for-flask-sessions
    volumes:
      - ./backend:/app
      - shared_data:/app/sessions
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
  shared_data: